name: Compile Solidity Contracts

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Compile contracts
      run: |
        npx solcjs --bin --abi --include-path node_modules/ --base-path . -o build contracts/HolaMundo.sol
